version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
       - db:/var/lib/postgresql/data

